# Generated by Django 6.0.3 on 2026-03-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0005_alter_category_level_alter_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor')], default='Student', max_length=20),
        ),
    ]
